version: "3"

services:
  frontend:
    image: seasonistas-frontend:latest
    environment:
      - NEXT_PUBLIC_API_URL=https://api.seasonistas.com
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: seasonistas-backend:latest
    environment:
      - PORT=4201
      - MONGO_URL=${MONGO_URL}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/letsencrypt/live/seasonistas.com:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
