version: "3"

services:
  frontend:
    image: seasonistas-frontend:latest
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4201
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: seasonistas-backend:latest
    ports:
      - "4201:4201"
    environment:
      - PORT=4201
      - MONGO_URL=${MONGO_URL}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
