export const initialJobs = [
    {
        id: 1,
        company: 'Linear company',
        logo: '/logos/linear.png',
        match: 86,
        applied: false,
        saved: true,
        title: 'UI/UX Designer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer to craft intuitive, centered designs for our digital platforms. You will be responsible for transforming user needs.',
        tags: ['Experience: 3 Year', 'Full Time', 'Salary: Monthly', 'Onsite Job', 'Other Detail'],
        rate: '$200/hr',
        location: 'Pakistan',
        time: '1 hour ago',
        date: '2025-05-21',
        status: 'Submitted',
        expireDate: '2025-06-30'
    },
    {
        id: 2,
        company: 'Spline studio',
        logo: '/logos/spline.png',
        match: 10,
        applied: false,
        saved: false,
        title: 'UI/UX Developer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 3 Year', 'Full Time', 'Salary: Monthly', 'Onsite Job', 'Other Detail'],
        rate: '$200/hr',
        location: 'Pakistan',
        time: '1 hour ago',
        date: '2025-05-21',
        status: 'Approved',
        expireDate: '2025-06-29'
    },
    {
        id: 3,
        company: 'Loom',
        logo: '/logos/loom.png',
        match: 99,
        applied: true,
        saved: true,
        title: 'Product Designer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 3 Year', 'Remote', 'Salary: Monthly', 'Other Detail'],
        rate: '$200/hr',
        location: 'India',
        time: 'Applied 1 hour ago',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-25'
    },
    {
        id: 4,
        company: 'Trainline',
        logo: '/logos/trainline.png',
        match: 78,
        applied: true,
        saved: false,
        title: 'Marketer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 2 Year', 'Full Time', 'Onsite', 'Other Detail'],
        rate: '$180/hr',
        location: 'India',
        time: 'Applied 2 hours ago',
        date: '2025-05-21',
        status: null,
        expireDate: '2025-06-24'
    },
    {
        id: 5,
        company: 'Raycast corp',
        logo: '/logos/raycast.png',
        match: 80,
        applied: false,
        saved: true,
        title: 'UI Designer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 4 Year', 'Full Time', 'Remote'],
        rate: '$210/hr',
        location: 'India',
        time: '3 hours ago',
        date: '2025-05-21',
        status: null,
        expireDate: '2025-06-28'
    },
    {
        id: 6,
        company: 'Notion',
        logo: '/logos/notion.png',
        match: 15,
        applied: false,
        saved: false,
        title: 'Backend Developer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 5 Year', 'Remote', 'Salary: Monthly', 'Other Detail'],
        rate: '$250/hr',
        location: 'India',
        time: '4 hours ago',
        date: '2025-05-21',
        status: 'Submitted',
        expireDate: '2025-06-26'
    },
    {
        id: 7,
        company: 'Dropbox',
        logo: '/logos/dropbox.png',
        match: 63,
        applied: true,
        saved: false,
        title: 'QA Engineer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 2 Year', 'Contract', 'Remote'],
        rate: '$150/hr',
        location: 'Pakistan',
        time: 'Applied Yesterday',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-27'
    },
    {
        id: 8,
        company: 'Figma Inc',
        logo: '/logos/figma.png',
        match: 90,
        applied: false,
        saved: true,
        title: 'Visual Designer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 3 Year', 'Onsite Job', 'Salary: Monthly'],
        rate: '$220/hr',
        location: 'Pakistan',
        time: '2 days ago',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-25'
    },
    {
        id: 9,
        company: 'Slack',
        logo: '/logos/slack.png',
        match: 55,
        applied: false,
        saved: false,
        title: 'Customer Support',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 1 Year', 'Remote', 'Full Time'],
        rate: '$100/hr',
        location: 'USA',
        time: '3 days ago',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-26'
    },
    {
        id: 10,
        company: 'Meta',
        logo: '/logos/meta.png',
        match: 88,
        applied: false,
        saved: true,
        title: 'Frontend Engineer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 3 Year', 'Remote', 'Full Time'],
        rate: '$300/hr',
        location: 'USA',
        time: '3 days ago',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-25'
    },
    {
        id: 11,
        company: 'Google',
        logo: '/logos/google.png',
        match: 92,
        applied: true,
        saved: false,
        title: 'DevOps Engineer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 4 Year', 'Remote', 'Contract'],
        rate: '$350/hr',
        location: 'USA',
        time: 'Applied 3 days ago',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-23'
    },
    {
        id: 12,
        company: 'Adobe',
        logo: '/logos/adobe.png',
        match: 78,
        applied: false,
        saved: false,
        title: 'Motion Designer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 3 Year', 'Full Time', 'Onsite'],
        rate: '$210/hr',
        location: 'UK',
        time: '4 days ago',
        date: '2025-05-21',
        status: 'Rejected',
        expireDate: '2025-06-30'
    },
    {
        id: 13,
        company: 'Spotify',
        logo: '/logos/spotify.png',
        match: 65,
        applied: false,
        saved: false,
        title: 'UX Researcher',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 2 Year', 'Remote', 'Full Time'],
        rate: '$190/hr',
        location: 'UK',
        time: '5 days ago',
        date: '2025-05-21',
        status: 'Approved',
        expireDate: '2025-06-26'
    },
    {
        id: 14,
        company: 'Netflix',
        logo: '/logos/netflix.png',
        match: 94,
        applied: false,
        saved: true,
        title: 'Creative Technologist',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 5 Year', 'Hybrid', 'Salary: Monthly'],
        rate: '$280/hr',
        location: 'UK',
        time: '5 days ago',
        date: '2025-05-21',
        status: 'Approved',
        expireDate: '2025-06-29'
    },
    {
        id: 15,
        company: 'Zoom',
        logo: '/logos/zoom.png',
        match: 50,
        applied: false,
        saved: false,
        title: 'SRE Engineer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 4 Year', 'Remote', 'Other Detail'],
        rate: '$270/hr',
        location: 'UK',
        time: '6 days ago',
        date: '2025-05-21',
        status: 'Approved',
        expireDate: '2025-06-28'
    },
    {
        id: 16,
        company: 'Trello',
        logo: '/logos/trello.png',
        match: 76,
        applied: true,
        saved: false,
        title: 'Support Engineer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 2 Year', 'Remote', 'Support'],
        rate: '$160/hr',
        location: 'UK',
        time: 'Applied 1 week ago',
        date: '2025-05-21',
        status: 'Approved',
        expireDate: '2025-06-27'
    },
    {
        id: 17,
        company: 'Canva',
        logo: '/logos/canva.png',
        match: 87,
        applied: false,
        saved: true,
        title: 'Interaction Designer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 3 Year', 'Onsite', 'Full Time'],
        rate: '$240/hr',
        location: 'UK',
        time: '1 week ago',
        date: '2025-05-21',
        status: 'Submitted',
        expireDate: '2025-06-26'
    },
    {
        id: 18,
        company: 'Github',
        logo: '/logos/github.png',
        match: 72,
        applied: false,
        saved: false,
        title: 'Full Stack Developer',
        description: 'We are seeking a creative and detail-oriented UI/UX Designer...',
        tags: ['Experience: 4 Year', 'Remote', 'Full Time'],
        rate: '$300/hr',
        location: 'UK',
        time: '1 week ago',
        date: '2025-05-21',
        status: 'Submitted',
        expireDate: '2025-06-25'
    }
];
