@baseUrl = http://localhost:4201/api

###
# @name QueryHealth
GET {{baseUrl}}/health
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdRegister
POST {{baseUrl}}/auth/register

{
  "email": "user2@gmail.com",
  "password": "pass",
  "role": "employer",
  "fullName": "User 2"
}

###
# -------------------------
# @name CmdLogin
POST {{baseUrl}}/auth/login

{
  "email": "user1@gmail.com",
  "password": "pass"
}
###
@accessToken = {{CmdLogin.response.body.$.token}}

###
# -------------------------
# @name QueryEmployerPostings
GET {{baseUrl}}/employer/my-postings
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdUpdateJobActiveStatus
PATCH {{baseUrl}}/job/674f55d17c5310d7dab48b36/update-status
Authorization: Bearer {{accessToken}}

{
  "isActive": true
}

###
# -------------------------
# @name QueryCommunity
GET {{baseUrl}}/community
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name QueryPostings
GET {{baseUrl}}/job/search
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdMarkPostingFavourite
PATCH {{baseUrl}}/mark-posting-favourite
Authorization: Bearer {{accessToken}}

{
  "postingId": "674f55d17c5310d7dab48b36",
  "isFavourite": true
}

###
# -------------------------
# @name QueryPostingFavourites
GET {{baseUrl}}/posting-favourites
Authorization: Bearer {{accessToken}}


###
# -------------------------
# @name CmdEmployeeApplyToPosting
POST {{baseUrl}}/job/apply
Authorization: Bearer {{accessToken}}

{
  "postingId": "674f55d17c5310d7dab48b36",
  "answers": []
}
