@baseUrl = http://localhost:4201/api

###
# -------------------------
# @name QueryHealth
GET {{baseUrl}}/health
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdTemp
POST {{baseUrl}}/temp

# ==================================
# ==================================
# ==================================
# ==================================
# ==================================

###
# -------------------------
# @name CmdRegister
POST {{baseUrl}}/auth/register

{
  "email": "user2@gmail.com",
  "password": "pass",
  "role": "employer",
  "fullName": "User 2"
}

###
# -------------------------
# @name CmdLogin
POST {{baseUrl}}/auth/login

{
  "email": "user2@gmail.com",
  "password": "pass"
}

###
@accessToken = {{CmdLogin.response.body.$.token}}

# ==================================
# ==================================
# ==================================
# ==================================
# ==================================

###
# -------------------------
# @name QueryCommunity
GET {{baseUrl}}/community
Authorization: Bearer {{accessToken}}

# ==================================
# ==================================
# ==================================
# ==================================
# ==================================

###
# -------------------------
# @name QueryEmployerPostings
GET {{baseUrl}}/employer/my-postings
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdEmployerCreatePosting
POST {{baseUrl}}/job/post
Authorization: Bearer {{accessToken}}

{,
  "title": "Software Automation Engineers needed",
  "description": "Experts who have the knowledge and ability to design, create, develop and manage machines and systems",
  "category": "Techonology",
  "specialism": "Software Engineering",
  "jobType": "fullTime",
  "expLevelRequired": "senior",
  "qualificationsRequired": [],
  "qualificationsDesired": [],
  "salaryMode": "monthly",
  "salary": "16000",
  "startDate": "2024-12-05T11:49:40.512Z",
  "endDate": "2024-12-05T11:49:40.512Z",
  "startTime": "2024-12-05T11:49:40.512Z",
  "endTime": "2024-12-05T11:49:40.512Z",

  "benefits": [],
  "workingLanguage": "en-US",
  "residence": "no",
  "food": "oneMeal",
  "transport": "notRequired",

  "companyName": "",
  "companyUsername": "",
  "companyDescription": "",
  "companyWebsite": "",
  "companyLogoUrl": "",
  "companyCountry": "",
  "companyCity": "",
  "companyArea": "",
  "companyZip": "",
  "companyMapAddress": "",

  "questions": [],
  "postedAt": "{{$datetime iso8601}}"
}

###
# -------------------------
# @name CmdEmployerUpdatePostingActiveStatus
PATCH {{baseUrl}}/job/6751950cfa37bcf420d2cc38/update-status
Authorization: Bearer {{accessToken}}

{
  "isActive": true
}

###
# -------------------------
# @name QueryAllPostings
GET {{baseUrl}}/job/search
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdMarkPostingFavourite
PATCH {{baseUrl}}/mark-posting-favourite
Authorization: Bearer {{accessToken}}

{
  "postingId": "6751950cfa37bcf420d2cc38",
  "isFavourite": true
}

###
# -------------------------
# @name QueryPostingFavourites
GET {{baseUrl}}/posting-favourites
Authorization: Bearer {{accessToken}}

###
# -------------------------
# @name CmdApplyToPosting
POST {{baseUrl}}/job/apply
Authorization: Bearer {{accessToken}}

{
  "postingId": "6751950cfa37bcf420d2cc38",
  "answers": []
}

###
# -------------------------
# @name CmdInviteEmployee
POST {{baseUrl}}/invite-employee
Authorization: Bearer {{accessToken}}

{
  "employeeId": "674f261e2b05a0cf3e0e3b87"
}

###
# -------------------------
# @name QueryIsEmployeeInvited
POST {{baseUrl}}/is-employee-invited
Authorization: Bearer {{accessToken}}

{
  "employeeId": "674f261e2b05a0cf3e0e3b87"
}

