name: Build and Transfer Client Application

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load environment variables
        id: load-env
        run: |
          source .github/env
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t seasonistas-frontend:latest ./client
          docker build -t seasonistas-backend:latest ./server

      - name: Save Docker images to tar files
        run: |
          docker save -o seasonistas-frontend.tar seasonistas-frontend:latest
          docker save -o seasonistas-backend.tar seasonistas-backend:latest

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Transfer images to server using password
        run: |
          sshpass -p "8=lpbO|yV7Qepw5z6Cg+" scp -o StrictHostKeyChecking=no seasonistas-frontend.tar root@145.223.116.46:/tmp/
          sshpass -p "8=lpbO|yV7Qepw5z6Cg+" scp -o StrictHostKeyChecking=no seasonistas-backend.tar root@145.223.116.46:/tmp/

      - name: Clean up local tar files
        run: |
          rm seasonistas-frontend.tar
          rm seasonistas-backend.tar
